version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - .env.production
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/nginx/cert:/etc/nginx/cert
